export const initialState = {
  posts: {
    data: {
      products: [
        { id: '1', status: 'published', title: 'Car', price: '50000', categories: ['Cars'], author: 'Damian Filipek', tel: '123-456-789', email: 'damianfilipek@gmail.com', editDate: '15.05.2021', creationDate: '15.05.2021', image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
        { id: '2', status: 'published', title: 'Wallet', price: '5', categories: ['Wallets'], author: 'John Doe', tel: '123-456-789', email: 'johndoe@gmail.com', editDate: '15.05.2021', creationDate: '17.06.2021', image: 'https://images.pexels.com/photos/915915/pexels-photo-915915.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
        { id: '3', status: 'published', title: 'Bike', price: '10000', categories: ['Bikes'], author: 'Jeremy Clarcson', tel: '123-456-789', email: 'jeremyclarcson@gmail.com', editDate: '15.05.2021', creationDate: '5.03.2021', image: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
        { id: '4', status: 'published', title: 'Motorcycle', price: '20000', categories: ['Motorcycles'], author: 'Damian Filipek', tel: '123-456-789', email: 'damianfilipek@gmail.com', editDate: '15.05.2021', creationDate: '01.04.2021', image: 'https://images.pexels.com/photos/2798288/pexels-photo-2798288.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
        { id: '5', status: 'published', title: 'Truck', price: '25000', categories: ['Cars', 'Trucks'] ,author: 'Damian Filipek', tel: '123-456-789', email: 'damianfilipek@gmail.com', editDate: '15.05.2021', creationDate: '15.05.2021', image: 'https://images.pexels.com/photos/2199293/pexels-photo-2199293.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
        { id: '6', status: 'published', title: 'Diamonds earrings', price: '10000', categories: ['Jewellery'], author: 'Damian Filipek', tel: '123-456-789', email: 'damianfilipek@gmail.com', editDate: '15.05.2021', creationDate: '15.05.2021', image: 'https://images.pexels.com/photos/2849743/pexels-photo-2849743.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
        { id: '7', status: 'published', title: 'Scooter', price: '5000', categories: ['Motorcycles'], author: 'Damian Filipek', tel: '123-456-789', email: 'damianfilipek@gmail.com', editDate: '15.05.2021', creationDate: '15.05.2021', image: 'https://images.pexels.com/photos/159192/vespa-roller-motor-scooter-cult-159192.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut semper ipsum. Curabitur nec ornare leo, sed pharetra turpis. Quisque eleifend et mi at laoreet. Maecenas a erat mi. Etiam et nisi arcu. Duis in luctus metus. Suspendisse potenti. Phasellus sodales ex odio, eu mollis nisl porttitor in. Nunc vestibulum quam vitae urna tincidunt, sit amet ultrices leo condimentum. Aliquam feugiat ornare dui, vel blandit tortor ornare ut. Vivamus ut lorem ornare, iaculis purus at, rutrum enim. Ut eros magna, gravida in justo semper, venenatis finibus quam. Quisque at orci quis augue lobortis congue tristique eu nisi. Suspendisse fermentum cursus velit, vel gravida leo condimentum a. Proin lobortis tellus et dapibus tincidunt.' },
      ],
      categories: [],
    },
    loading: {
      active: false,
      error: false,
    },
  },
  users: {
    loggedOut: false,
    loggedIn: true,
    admin: false,
    email: 'damianfilipek@gmail.com',
  },
  searchString: '',
};
